In [11]:
import os
import cv2
import numpy as np
path = os.getcwd()+"/Ressam/"
folderNames = os.listdir(path)
XSample, ySample = [], []

for i, folderName in enumerate(folderNames):
    folderPath = os.path.join(path, folderName)
    if os.path.isdir(folderPath):  # Yalnızca dizinleri işleyin
        for j, file in enumerate([f for f in os.listdir(folderPath)
                                  if os.path.isfile(os.path.join(folderPath, f)) and f != ".DS_Store"]):
            img = cv2.resize(cv2.imread(os.path.join(folderPath, file)),
                             (128, 128), interpolation=cv2.INTER_LINEAR) / 255.0
            XSample.append(np.asarray(img))
            ySample.append(i-1)
XSample = np.array(XSample)
ySample = np.array(ySample)
print(XSample.shape)
print(ySample.shape)

(825, 128, 128, 3)
(825,)


In [12]:
print(XSample)

[[[[0.24705882 0.45490196 0.58431373]
   [0.33333333 0.5372549  0.6627451 ]
   [0.09803922 0.23137255 0.32941176]
   ...
   [0.4627451  0.58431373 0.44313725]
   [0.47058824 0.60392157 0.47058824]
   [0.49803922 0.58823529 0.45490196]]

  [[0.38823529 0.60392157 0.7254902 ]
   [0.27058824 0.45490196 0.57647059]
   [0.19607843 0.3254902  0.41176471]
   ...
   [0.50980392 0.60392157 0.4627451 ]
   [0.53333333 0.63137255 0.47843137]
   [0.52156863 0.59607843 0.46666667]]

  [[0.29019608 0.52156863 0.65882353]
   [0.26666667 0.44313725 0.57647059]
   [0.19607843 0.3372549  0.43529412]
   ...
   [0.55294118 0.60392157 0.45490196]
   [0.56470588 0.61568627 0.46666667]
   [0.60392157 0.65490196 0.50588235]]

  ...

  [[0.2627451  0.42745098 0.60784314]
   [0.16078431 0.30196078 0.48627451]
   [0.14509804 0.2745098  0.45882353]
   ...
   [0.23529412 0.27843137 0.23529412]
   [0.31372549 0.38039216 0.34509804]
   [0.2627451  0.37254902 0.40392157]]

  [[0.38039216 0.6        0.70980392]
   [0.2

In [13]:
print(ySample)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [14]:
from sklearn.model_selection import train_test_split
XTrain,XTest,yTrain,yTest = train_test_split(XSample,ySample,test_size=0.1,random_state=0)
XTrain,XVal,yTrain,yVal = train_test_split(XTrain,yTrain,test_size=0.11,random_state=0)
print(XTrain.shape)
print(XTest.shape)
print(XVal.shape)

(660, 128, 128, 3)
(83, 128, 128, 3)
(82, 128, 128, 3)
